#!/bin/bash

case $1 in
abiword) abiword ;;
alsamixer) xterm -e alsamixer ;;
alsaplayer) alsaplayer ;;
asunder) asunder ;;
beaver) beaver  ;;
bitbucket) browser http://bitbucket.org/ ;;
bootfloppybox) subox bootfloppybox ;;
bootlog) xterm -hold -title 'boot.log (shift-pgup/pgdn to scroll)' -e 'bootlog' ;;
burnbox) burnbox ;;
burnbox-doc) browser file:///usr/share/doc/slitaz-tools/burnbox.html ;;
chess) url=file:///var/www/chess/index.html ; tazweb --notoolbar $url || browser $url ;;
codeblocks) codeblocks  ;;
cookutils-doc) browser file:///usr/share/doc/cookutils/cookutils.html ;;
cups) htmlview http://localhost:631/ ;;
desktopbox-autostart) desktopbox autostart ;;
desktopbox-tazapps) desktopbox tazapps ;;
dialog) xterm -e dialog --title " Title " --msgbox "Message box" 8 60 ;;
epdfview) epdfview  ;;
fluid) fluid ;;
galculator) galculator ;;
gcolor2) gcolor2 ;;
google-chrome) /opt/google/chrome/google-chrome  ;;
google-chrome) /opt/google/chrome/google-chrome ;;
google-chrome) /opt/google/chrome/google-chrome --incognito ;;
gparted) subox gparted ;;
gpl-license) browser file:///usr/share/licenses/gpl.txt ;;
hardinfo) hardinfo ;;
httpd-cgi) browser http://localhost/cgi-env.sh ;;
httpd) browser http://localhost/ ;;
i3) i3 ;;
isomaster) isomaster ;;
jamendo) browser http://www.jamendo.com/ ;;
leafpad) leafpad  ;;
libreoffice-base) libreoffice3.6 --base  ;;
libreoffice-base) libreoffice --base  ;;
libreoffice-calc) libreoffice3.6 --calc  ;;
libreoffice-calc) libreoffice --calc  ;;
libreoffice-draw) libreoffice3.6 --draw  ;;
libreoffice-draw) libreoffice --draw  ;;
libreoffice-impress) libreoffice3.6 --impress  ;;
libreoffice-impress) libreoffice --impress  ;;
libreoffice-math) libreoffice3.6 --math  ;;
libreoffice-math) libreoffice --math  ;;
libreoffice-printeradmin) libreoffice3.6-printeradmin ;;
libreoffice-writer) libreoffice3.6 --writer  ;;
libreoffice-writer) libreoffice --writer  ;;
lostirc) lostirc ;;
lua) xterm -e lua ;;
lxappearance) lxappearance ;;
lxrandr) lxrandr ;;
lxtask) lxtask ;;
mhwaveedit) mhwaveedit ;;
midori) midori  ;;
midori-private) midori --private  ;;
mountbox) subox mountbox ;;
mtpaint) mtpaint ;;
mtpaint-grab) mtpaint -s ;;
nano) xterm -e nano ;;
netbox) subox netbox ;;
obconf) obconf  ;;
openbox) openbox ;;
parcellite) parcellite ;;
passwd) xterm -T "Passwd" -geometry 60x10 -e 'echo; passwd; sleep 4' ;;
pcmanfm) pcmanfm  ;;
pcmanfm-find) pcmanfm --find-files  ;;
pcmanfm-folder-handler) pcmanfm  ;;
pcmanfm-pref) pcmanfm --show-pref=3 ;;
python) xterm -e python ;;
retawq) xterm -e retawq ;;
sakura) sakura ;;
scpbox) scpbox ;;
serverbox) subox serverbox ;;
shell-profile) edit-dot-profile ;;
slitaz-logout) tazbox logout ;;
sqlite) xterm -e sqlite3 ;;
sshbox) sshbox ;;
sudoku) url=file:///var/www/sudoku/index.html ; tazweb --notoolbar $url || browser $url ;;
system-doc) browser file:///usr/share/doc/slitaz/index.html ;;
tazbox-keymap) tazbox su "tazbox keymap" ;;
tazbox-locale) tazbox su "tazbox locale" ;;
tazbox-tz) tazbox su "tazbox tz" ;;
tazbug) tazbug-box ;;
tazhw-box) subox 'tazhw box' ;;
tazinst-doc) browser file:///usr/share/doc/slitaz-tools/tazinst.html ;;
tazlito-doc) browser file:///usr/share/doc/tazlito/tazlito.html ;;
tazlito-wiz) subox tazlito-wiz ;;
tazpanel) browser http://tazpanel:82/ ;;
tazpanel-pkgs) tazweb http://tazpanel:82/pkgs.cgi ;;
tazpkg-box) tazbox su tazpkg-box actions  ;;
tazpkg-doc) browser file:///usr/share/doc/tazpkg/tazpkg.html ;;
tazusb-box) tazbox su tazusb-box ;;
tazweb) tazweb  ;;
tazwikiss) browser http://localhost/wiki/index.sh ;;
transmission) transmission  ;;
twitter) browser http://twitter.com/ ;;
vi) terminal vi ;;
viewnior) viewnior  ;;
wifibox) tazbox su wifibox ;;
wikipedia) browser http://www.wikipedia.org/ ;;
Xdefaults) edit-dot-xdefaults ;;
xterm) xterm -ls ;;
yad-icon-browser) yad-icon-browser ;;
zoho-viewer) browser http://viewer.zoho.com/ ;;
esac
